project:
  type: website

website:
  title: "posit::conf(2024)"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:conference_talks
    right:
      - about.qmd
  sidebar: 
    - id: conference_talks
      title: Conference talks
      style: "docked"
      contents: 
        - auto: conference_talks

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true