project:
  type: website

website:
  title: "posit::conf(2024)"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:conference_talks
    right:
      - about.qmd
  sidebar: 
    - id: conference_talks
      title: Conference talks
      style: "docked"
      contents: 
        - text: "Takeaways"
          href: conference_talks/takeaways.qmd
        - section: "Keynotes"
          contents:
            - auto: "conference_talks/keynotes/*.qmd"
        - section: "Other talks"
          contents:
            - auto: "conference_talks/other_talks/*.qmd"
        - section: "Tips and tricks learnt from conference"
          contents:
            - auto: "conference_talks/tipsandtricks/*.qmd"
        
            

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true