project:
  type: website
  pre-render: "echo Let the rendering begin!"
  # post-render: "Rendering done!"

website:
  title: "posit::conf(2024)"
  bread-crumbs: false
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:conference_talks
    right:
      - about.qmd
  sidebar: 
    - id: conference_talks
      title: Conference talks
      style: "docked"
      collapse-level: 1
      contents: 
        - section: "Takeaways"
          contents:
            - conference_talks/whats_new.qmd
            - conference_talks/tipsandtricks.qmd
        - section: "Keynotes"
          contents:
            - auto: "conference_talks/keynotes/*.qmd"
        - section: "Other talks"
          contents:
            - auto: "conference_talks/other_talks/*.qmd"
        
format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true