project:
  type: website
  pre-render: "echo Let the rendering begin!"
  # post-render: "Rendering done!"

website:
  title: "posit::conf(2024)"
  repo-url: https://github.com/mathiaslj/posit_conf_2024_notes
  repo-actions: [source]
  back-to-top-navigation: true
  bread-crumbs: false
  navbar:
    left:
      - href: workshop.qmd
        text: Workshop
      - sidebar:conference_talks
      - sidebar:takeaways
    right: 
      - icon: github
        href: https://github.com/mathiaslj/posit_conf_2024_notes
      
  sidebar: 
    - id: takeaways
      title: Takeaways
      style: "docked"
      collapse-level: 1
      contents:
        - section: "Takeaways"
          contents:
            - conference_talks/whats_new.qmd
            - conference_talks/tipsandtricks.qmd
            
    - id: conference_talks
      title: Conference talks
      style: "docked"
      collapse-level: 1
      contents: 
        - section: "Keynotes"
          contents:
            - auto: "conference_talks/keynotes/*.qmd"
        - section: "Other talks"
          contents:
            - auto: "conference_talks/other_talks/*.qmd"
        
format:
  html:
    theme: 
      - flatly
      - styles.scss
    toc: true