---
title: "Updates from Posit"
---

[Link to video](https://reg.conf.posit.co/flow/posit/positconf24/publiccatalog/page/publiccatalog/session/1712004520449001rbm2)

Speakers:

-   Hadley Wickham, Chief Scientist, Posit
-   James Blair, Senior Product Manager, Posit
-   Charlotte Wickham, Developer Educator, Posit
-   George Stagg, Software Engineer, Posit

## Session description

*Please join us for our first Posit keynote, where we’ll tell you about our mission, our products, and some of the exciting things we’ve been working on over the last year. Hadley Wickham, Chief Scientist, will talk briefly about Posit’s mission and products, before introducing the three speakers who will update you on some of the coolest projects we’ve worked on over the last year. James Blair, Senior Product Manager, will give you the latest on our partnerships with Databricks and Snowflake, and how we’re building seamless integrations that let you focus on data science instead of dealing with technical details. Charlotte Wickham, Developer Educator, will show you what’s new in Quarto, focusing on new ways to build beautiful PDFs with Typst. Finally, George Stagg, Senior Software Engineer, will tell you about the latest innovations in teaching using webR, a tool that lets you compile your R code into standalone HTML files.*

## Session notes

### Future of Quarto

-   Lots new features for [quarto dashboards](https://quarto.org/docs/dashboards/)
-   [typst](https://quarto.org/docs/output-formats/typst.html) for PDF creation rather than LaTeX
    -   typst ensures transformation of CSS behind HTML to typst properties than ensures HTML and PDF look exactly similar
    
### webR, shinylive and Quarto live

-   [webR](https://webr.r-wasm.org/latest/) is a javascript app that allows running of R code directly in browser.
-   [shinylive](https://posit-dev.github.io/r-shinylive/) is an R package that enables way of running Shiny entirely in a browser using webR.
    -   Embed shinylive in quarto using [quarto extension](https://quarto-ext.github.io/shinylive/)
-   [Quarto live](https://github.com/r-wasm/quarto-live) quarto extension which enables interactive documents and code exercises in quarto documents
    -   Options of setup blocks, targeted feedback and much more available
    -   Great way to create educational material

### Snowflake and databricks

#### Infrastructure management

-   [Posit workbench](https://posit.co/products/enterprise/workbench/) available in [Snowflake](https://www.snowflake.com/en/) marketplace
    -   Give users access to workbench directly through existing Snowflake infrastructure
    -   Version of workbench automatically update when new there is new release
    -   Low maintenance, hands-off approach to give users what they need
    
Posit will work with other cloud data platforms to provide similar experience in other environments

#### Data access

-   New [`databricks`](https://odbc.r-dbi.org/reference/databricks.html) and [`snowflake`](https://odbc.r-dbi.org/reference/snowflake.html) functions in `odbc` package for easier connections.
-   Users can sign in to databricks or snowflake on Posit workbench, and then workbench will manage credentials on the users behalf.
    -   No longer have to think about access tokens, passwords - how to manage those, pass them into the connection, etc.
    -   Works with `odbc` but also `sparklyr` and interaction with `spark` in databricks

#### Authentication in apps

One solution is to create service account with an access token that runs the app. However, two limitations:

-   Users will see data based on permission set of service account.
-   With number of apps growing, so is number of service account with tokens that need managing

New solution: Integrated authetication as described above but in Posit Connect
-   As a viewer, you log in to fx. databricks, and you will then only be able to see data that you are authorised to see through you permissions on your databricks account.